### ISSUE TITLE
Warning when exiting with unsaved changes

### ISSUE THREAD

**Issue by silvanheller** [dres-dev/DRES#102]
Since changes to a competition are not automatically saved, it would be nice to receive a warning popup before closing the tab. I think the best way to implement this would be something like [this SO answer](https://stackoverflow.com/a/61404006)

**Comment by lucaro** [comment]
Just tested it in most recent version and did not receive a warning.

**Comment by sauterl** [comment]
I can confirm this behaviour and will take a look at it

**Comment by sauterl** [comment]
The culprit is, that we do not have the commit on `dev`, a simple merge of master into dev will solve this.
