### ISSUE TITLE
[Run Admin View] Task Overview w/ Task Description

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#126]
Request to add the task description to the task selection / task overview of an ongoing run

**Comment by ppanopticon** [comment]
You mean in the RunAdminView (i.e. /run/admin)?

**Comment by sauterl** [comment]
I'm closing this for now, as most information is given (type, group, ... ) and more information is unreasonably to show, as this depends on the task type. Also, I honestly do not remember what the exact requirement was
