### ISSUE TITLE
Competition Run Admin View Improvements

### ISSUE THREAD

**Issue by lucaro** [dres-dev/DRES#131]
- [x] Show visual indicator for already used tasks
- [x] ~~Add option to change the order of the tasks in the UI See #220~~
- [x] Hide 'jump to task' buttons while a task is active
- [x] Show which user and IP is associated to which viewer
- [x] Show users in team list
- [x] Make team icons rectangular rather than round

**Comment by sauterl** [comment]
Ad 5 & 6: See #136

**Comment by sauterl** [comment]
Ad 2: This was introduces sometime ago by @ppanopticon

**Comment by lucaro** [comment]
How can the order of the tasks in the UI be changed?

**Comment by sauterl** [comment]
@lucaro That's a misunderstanding from my point: Recently I did some cleanup of the tasks and realised, that one can change the order of tasks _during a run_.
Upon competition building, this is afaik not possible

**Comment by lucaro** [comment]
Exactly, but having the option to reorder the tasks would be very convenient nevertheless.
