### ISSUE TITLE
[Future Work] Asynchronous Competition Run Notes

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#151]
This is a list of things to consider when implementing (some time in the future) asynchronous competition runs:

 - [ ] Decouple Tasks  & Runs
 - [ ] Have dedicated UI for "completed" tasks (i.e. another task viewer)
 - [ ] Appropriate API endpoints
 - [ ] Task Run automation: Starting _next_ task automatically

**Comment by lucaro** [comment]
I am closing this since all entries are already addressed or tracked somewhere else.
