### ISSUE TITLE
Test HTTP and HTTPS behaviour

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#159]
Sophisticated test of behaviour when HTTPS is disabled.
Especially the submission component of the system might have to handle HTTP requests

**Comment by lucaro** [comment]
I tested the submission mechanism using the most basic HTTP setup I could think of, using
```bash
printf "GET /submit?session=...sessionid...&item=00001&timecode=00:01:10:00 HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n" | nc 127.0.0.1 80
```
and was able to submit successfully. The only header field which needs to be set, apart from the actual request, is the host field. No HTTPS capable client is required, even if HTTPS the upgrade option is used.

Therefore, I'd argue that this is not an issue.
