### ISSUE TITLE
[Task Viewer] Configure Slideshow after Task Completed

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#160]
There are two parameters for the "slideshow" once a task has completed.
Currently, these are hardcoded and should be configurable:

 - [x] Looping
 - [x] Delay in between items

**Comment by ppanopticon** [comment]
Review functionality and set reasonable defaults. Slideshows should be looping by default and there should be a reasonable pause in between.

**Comment by ppanopticon** [comment]
I have adjusted the implementation accordingly but needed to make certain assumptions:

- Images are displayed for 3 seconds (this is a constant, could be configurable in the future).
- Videos are displayed for as long as the video(-segment) takes (this is not configurable).
- In between two elements, there is always a one second pause (this is configurable, however, see limitation one bellow).

There is certain limitations in the current implementation that we might want to address in the future:

1. The current implementation does not allow for sub-second durations. This is problematic, however, refactoring this would require a range of changes in the backend and the UI and affects task creation as well as task playback.
2. Per MediaItem configuration is neither supported by the data model nor the current task builder.

**Comment by lucaro** [comment]
What's the reasoning behind adding a 1s gap between the element?

**Comment by ppanopticon** [comment]
There is two reasons:

- I need an EMPTY element with an explicit offset at the end of every list so that I can determine how long video segments should be displayed. 
- For the sake of simplicity I added a 1s EMPTY element after every element, which is just an assumption that there is a pause between two elements of the slideshow.

**Comment by lucaro** [comment]
So the video is only displayed once rather than looped?

**Comment by ppanopticon** [comment]
Technically, the slideshow element that contains the video is displayed for as long as the video plays. After that, it fades to EMPTY and then it starts over (or moves to next slideshow element).

**Comment by lucaro** [comment]
I see, as long as the slideshow loops, that makes sense.
