### ISSUE TITLE
Backend ffmpeg link

### ISSUE THREAD

**Issue by klschoef** [dres-dev/DRES#168]
In the distribution folder of the backend, a symbolic link to ffprobe needs to be created (as ext/ffmpeg/ffprobe), this is not clear from the Readme documentation. It is also confusing that there already is an "external" folder, which is empty though.

=> Please document this.

**Comment by lucaro** [comment]
Yes, this is currently a limitation with the gradle task which gets the dependency. The dependencies are not packaged together with the distribution, so when you unpack the zip or tar, they are not where the system expects them. You don't need to symlink the files, you can also just move the 'ext' directory. We'll update the gradle task accordingly.

**Comment by sauterl** [comment]
Moved to #186
