### ISSUE TITLE
Stabilisation: Prevent multiple active runs of one competition

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#182]
Currently the system enables multiple concurrent runs of a single competition. This could lead to corrupt data and should be prevented

**Comment by ppanopticon** [comment]
This should be handled by commit b53185b, isn't it?

**Comment by sauterl** [comment]
It is not yet thoroughly tested - that‘s why this issue is still open. I will flag it as ‚dev‘ as soon as I have been able to test it

On 24 Nov 2020, at 23:20, Ralph Gasser <notifications@github.com> wrote:

﻿

This should be handled by commit b53185b<https://github.com/dres-dev/DRES/commit/b53185b1ed557a4bca459058ef1f9f1ab7913037>, isn't it?

**Comment by sauterl** [comment]
You were right, it got fixed with b53185b
