### ISSUE TITLE
[Deployment] Revisit Deployment Automation

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#186]
A collection of tasks related to deployment and its automation

- [x] FFmpeg integration / better way to handle external dependency to FFmepg and FFmprobe (formerly #168 )
- [x] Adjust the application settings in gradle to give the deployment more memory by default (i.e. 4GiB) (formerly #181)
- [x] Rename deployment artefact to `dres` (currently it's called `backend`, which is not very descriptive)
- [x] Revisit deployment process and check whether it is still working the way intended.
- [x] Ultimately, adjust the README / guide accordingly

**Comment by ppanopticon** [comment]
**Ad FFMpeg:** FFMpeg is not included in distribution during packaging.
