### ISSUE TITLE
OpenAPI specification for submission and logging endpoints

### ISSUE THREAD

**Issue by lucaro** [dres-dev/DRES#197]
We should have a dedicated OpenAPI specification file for just the API endpoints which are relevant to the systems submitting to the server in order to simplify client development.

 - [x] Add OpenAPI specs for logging and submission endpoints to README
 - [x] Add OpenAPI specs for logging and submission endpoints to wiki
 - [ ] Test client generated code and add documentation on how to use it

**Comment by sauterl** [comment]
They are already in the [`/doc`](https://github.com/dres-dev/DRES/tree/master/doc) folder in our repository.
I guess we could add swagger-editor badges and mention them more prominently in the readme / wiki.

Also, testing these would be a thing

**Comment by lucaro** [comment]
We would probably also want a process to generate them (more or less) automatically

**Comment by sauterl** [comment]
I recently implemented an approach to have those generated automatically and failed, since there aren't multiple OpenApiPlugins allowed in javalin.
However, I asked there what they think: https://github.com/tipsy/javalin/issues/1108

**Comment by sauterl** [comment]
Ultimately, this is now coupled with tipsy/javalin#1117 and #206

**Comment by sauterl** [comment]
Moved to milestone 0.6-alpha due to dependency to #206
