### ISSUE TITLE
Whishlist of metrics DRES automatically computes, displays and provides for download

### ISSUE THREAD

**Issue by cristinailli** [dres-dev/DRES#200]
Designing an evaluation for the vitrivr system, these metrics have been identified to be interesting and could als be interesting for other, general purpose evaluation / competitions.
Most of these metrics could be displayed live, e.g. in a "statistics" view of the frontend. However, it's mandatory that these are downloadable from some endpoint (or at least exportable from the CLI). Other metrics are heavily dependent on interaction logging.

- [x] number of correct submissions
- [x]  time to correct submission
- [x]  number of incorrect submissions before correct submission
- [x] number of wrong segments, but correct video (tells more about how competent the user is rather than about my contributions)
- [x]  aggregation over team scores: average, max. score achieved, max. position of correct segment (Updated)
(e.g. teams 1&2&3 combined vs. teams 2&3&4 combined)
- ~number of times a functionality in the UI was used~
    * ~"result set info"~
    * ~"add tag to query"~
    * ~"feature data for individual element"~
- [x]  number of times correct segment was found & displayed but overlook by user
- ~query reformulations:~ 
    * ~number of reformulations~
    * ~which other 'query type' was used instead of tags?~
- [x]  position of correct segment 
- [x]  score of correct segment in user's result set
- ~number of correct submissions that used new additions ('new additions' needs to be specified in interaction logging or so)~
- ~which existing functionality was used alternatively to new additions?~

**Comment by sauterl** [comment]
Bullets 1 - 3 handled on [`dev`](https://github.com/dres-dev/DRES/tree/dev), by writing in a csv., see ef9f80e9772ee0dd883743b2196bbd888aae2ac1

**Comment by sauterl** [comment]
@cristinailli We had a look at your issue and labelled bullets not achievable within DRES as such.

**Comment by cristinailli** [comment]
@lucaro @sauterl I updated the wishlist with a more concrete example for team scores analysis
