### ISSUE TITLE
Update Javalin to use latest stable version >3.12.0

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#206]
Currently, we're using 3.8.x and thus, are 4 minor versions behind.

**Comment by lucaro** [comment]
Assuming tipsy/javalin#1117 will be part of 3.13.0, it probably makes sense to wait for the next release.

**Comment by sauterl** [comment]
This will also fix [another issue](https://github.com/tipsy/javalin/issues/1079)
