### ISSUE TITLE
Time Series for Scores

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#209]
Development of scores over time, ideally per task group **and** overall score. Originated in #194

**Comment by ppanopticon** [comment]
Separate component / dedicated view (first iteration).

**Comment by ppanopticon** [comment]
There is now a dedicated view that allows for visualization of the temporal development of different scoreboards. Open questions in need of discussion:

- How often should this view be updated?
- How often should scores be re-calculated?
- Integration with existing views?
- Look & feel
