### ISSUE TITLE
Github Actions: Add dev label automatically

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#210]
Properly add https://github.com/marketplace/actions/fixed-issues-labeler

**Comment by ppanopticon** [comment]
So I tried multiple thinks and the way I see it the action gets executed but doesn't seem to recognise the need for labeling. My best guess would be that the plugin is broken, which makes sense: Last commit is from 9 months ago.

**Comment by lucaro** [comment]
Appears not to work as expected, closing for now.
