### ISSUE TITLE
FFmpeg not found in deployment

### ISSUE THREAD

**Issue by cristinailli** [dres-dev/DRES#215]
Using deployment from distZip, DRES has to be started from within bin/-folder otherwise the following issue occurrs on branch master:

```
DRES> quit
Exception in thread "main" java.lang.ExceptionInInitializerError
	at dev.dres.DRES.main(DRES.kt:60)
Caused by: java.lang.IllegalStateException: Could not find valid FFmpeg binary path.
	at dev.dres.utilities.FFmpegUtil.<clinit>(FFmpegUtil.kt:25) 
```

**Comment by ppanopticon** [comment]
Can anyone reproduce this issue? It seems to work on my machine.

**Comment by lucaro** [comment]
Try starting it from a different directory than the binary is in

**Comment by sauterl** [comment]
yeah, I can confirm this behaviour on a fresh Ubuntu 20.04 installation. Steps to reproduce:

1. Clone DRES `git clone https://github.com/dres-dev/DRES.git`
2. Build DRES `./gradlew build`
3. Copy & extract dist: `cp backend/build/distribution/dres-dist.zip .` and `unzip dres-dist.zip` (and copying the default keystore to make it work `cp backend/keystore.jks .`
4. Run the deployment `./dres-dist/bin/dres`
5. `DRES> quit` yields the same error as above

**Comment by ppanopticon** [comment]
I created a solution which is not really nice, but seems to do the trick at least for the two cases where I either run a distribution (maybe even in a Docker container) or run DRES in the IDE.
