### ISSUE TITLE
API: Add connection check endpoint

### ISSUE THREAD

**Issue by silvanheller** [dres-dev/DRES#216]
It would be nice to have a dummy endpoint where systems can verify that they are indeed (i) authenticated and (ii) can submit requests to DRES using e.g. `withCredentials` headers.

I imagine a simple rest endpoint which is something like /test or /verifyLogin and which returns a 200 if authentication is successful and maybe even some information about the user which submitted a request.

The use case is pretty simple: I'd like to show in the frontend of vitrivr-ng if a user is authenticated when DRES is enabled in the config and otherwise show a warning.

**Comment by lucaro** [comment]
You can use the `/api/user` endpoint for that, which returns the details of the user who is currently signed in.

**Comment by silvanheller** [comment]
Works for my use case, thanks!
