### ISSUE TITLE
Documentation: Add Certification Setup to Deployement Guide

### ISSUE THREAD

**Issue by silvanheller** [dres-dev/DRES#217]
It would be useful to briefly add a few words about generating the keystore file somewhere in the documentation. 
The setup is relatively trivial, certbot detects e.g. apache installations. The setup for my current node was simply executing `certbot`, following the process, and the using the following steps to generate the `keystore.jks` file (thanks @lucaro):

```
sudo certbot certonly --standalone --preferred-challenges http -d <domain>
sudo cat /etc/letsencrypt/live/<domain>/*.pem > fullchain.pem
openssl pkcs12 -export -out fullchain.pkcs12 -in fullchain.pem
keytool -genkey -keyalg RSA -alias sfdcsec -keystore keystore.jks
keytool -delete -alias sfdcsec -keystore keystore.jks
keytool -v -importkeystore -srckeystore fullchain.pkcs12 -destkeystore keystore.jks -deststoretype JKS
```

The cert is then valid for the entire domain, and it is no problem running DRES on non-default HTTPS ports.

**Comment by lucaro** [comment]
This is technically not strictly related to DRES, as java key store files have been around for a long time. It might however be useful to add this to the deployment documentation as an example.

**Comment by lucaro** [comment]
Done, see https://github.com/dres-dev/DRES/wiki/Advanced-Setup-Options
