### ISSUE TITLE
Automate OpenAPI generation

### ISSUE THREAD

**Issue by lucaro** [dres-dev/DRES#224]
- [x] Remove openapi frontend bindings from repo
- [x] Add process to generate frontend & **client** OpenApi specs
- [x] Add process to use said OAS to generate frontend bindings

**Comment by sauterl** [comment]
Upon changes in the openapi, for developers execute these gradle tasks:

`./gradlew generateOAS` (generates the OpenApi specs)
`./gradlew openApiGenerate` (generates the actual bindings)

Also, generate the client OAS:

`./gradlew generateClientOAS`
