### ISSUE TITLE
Color picker in competition editor

### ISSUE THREAD

**Issue by lucaro** [dres-dev/DRES#232]
Replace the currently used native color picker for team colors and replace it with an angular one. It would ideally also offer a reasonable set of default colors.

**Comment by ppanopticon** [comment]
What exactly is the reasoning behind this request? I just tested _ngx-color-picker_, which we're also using for vitrivr. 

There is no advantage whatsoever over just using the native color picker. Is there some specific functionality we need here?

**Comment by lucaro** [comment]
Apart from the native color picker being os-dependent and therefore inconsistent, it does not offer the ability to define a color palette which I think would greatly benefit the overall look and feel, if we defined it to be consistent with the rest. (Also, the native color picker looks like a dialog from the mid 90ies, at least on windows.)

**Comment by ppanopticon** [comment]
I'm not aware of any color picker that offers color palettes out of the box. So we'd have to create this functionality manually If we're to do that, then probably should have a discussion about the how.

What I can do is integrate _ngx-color-picker_. That would address the consistency issue.

**Comment by lucaro** [comment]
At least the one used in vitrivr-ng appears to have an easy way to define a preset of colors, see https://github.com/vitrivr/vitrivr-ng/blob/master/src/app/query/containers/images/sketch-dialog.component.ts#L20 and https://github.com/vitrivr/vitrivr-ng/blob/master/src/app/query/containers/images/sketch-dialog.component.html#L38

**Comment by ppanopticon** [comment]
I stand corrected.

Implemented the change. Feel free to design your color palette in competition-builder-team-dialog.component.ts on line 20.
