### ISSUE TITLE
Upgrade Angular + Angular Material to latest Version

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#237]
We're currently using Angular + Angular Material 9.x. However, latest stable release is 11.2.4 and 11.2.2 for Angular and Angular Material, respektively. To not further fall behind, I suggest to update our frontend.

**Comment by ppanopticon** [comment]
I have pushed _Angular_ and _Angular Material_ to version 11, which is the current LTS version and should be supported until May 2022.

While being at it, I have also pushed some other dependencies.
