### ISSUE TITLE
JLine causes EndOfFileException in Docker

### ISSUE THREAD

**Issue by ppanopticon** [dres-dev/DRES#239]
JLine causes an _EndOfFileException_ when run in a Docker container that is not interactive (i.e. without the -it flag). This seems to be expected behaviour from JLine's side, since Docker does not provide an open input stream for the terminal. 

Due to the nature that JLine integrates with the rest of DRES, the issue basically renders DRES unusable in this case. Maybe we should think about retrofitting DRES to be able to run in a headless mode, especially since more and more functionality becomes available from the Web UI.

**Comment by lucaro** [comment]
Sure, that should be reasonably straight forward, although this would currently result in a bootstrapping problem, since you need a admin user to use the web UI, the first one of which can only be created via the CLI.

**Comment by sauterl** [comment]
I guess enabling certain commands to be called from the start, could solve this bootstrapping issue:
For instance, with thr bewly added `exec` command, one could easily provide a script to add the first view things (e.g. admin user etc).

Alternatively we could ship with a default root user, whose password is configured via the condig file.

(I'm trying the github mobile app, might mess up the formatting)
