### ISSUE TITLE
[CLI] Generate/Import competition description from run

### ISSUE THREAD

**Issue by lucaro** [dres-dev/DRES#245]
Ideally, one would be able to import a previous run as a competition in order to be able to run it again.

**Comment by sauterl** [comment]
Ideally, there is a competition importer, whose UI / interface is also able to import the competition of a run (and discard the _run_ information). Also inform the users about what has happened.

Officially, this will be the **Competition Importer**

**Comment by ppanopticon** [comment]
This has been added on dev. 

Currently, it is an explicit flag that must be set in competition import. Do we need an 'auto-detect' feature here?

**Comment by ppanopticon** [comment]
Implemented!
