### ISSUE TITLE
keystore.jks is not a valid keystore

### ISSUE THREAD

**Issue by nikkiwoo-gh** [dres-dev/DRES#248]
Hi.
Firstly, thank you so much for sharing this VBS server project.
I has successfully build up the backend, and keep "enableSsl" : false" as default.
but when I run the backend script on the localhost, this problem "keystore.jks is not a valid keystore" appears.
Could you tell me how to fix it? Thanks

P.S. I also try enable SSL and set keystorePath as localhost.jks, but it did not work.

**Comment by sauterl** [comment]
Hi there

First of all, what do you mean exactly by

> ... run the backend script on the localhost ...

Did you build the backend as described in the readme and started it properly via the distribution?

The default config expects the `keystore.jks` that we provide (https://github.com/dres-dev/DRES/blob/master/backend/keystore.jks) in the current working directory.
So, if you have your `dres-dist` unzipped and start DRES by `./dres-dist/bin/backend`, it expects the keystore at `./keystore.jks`.

However, if you want to setup a proper SSL enabled DRES, please follow these steps from the wiki:
https://github.com/dres-dev/DRES/wiki/Advanced-Setup-Options

**Comment by nikkiwoo-gh** [comment]
After putting "keystore.jks" to the current directory, everything works fine.
Thank you so much
