### ISSUE TITLE
Viewer Countdown

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#268]
Slightly adjust messages when waiting

1. Display "Waiting for other viewers to be ready"
2. Display "All viewers ready"
3. Start countdown

**Comment by ppanopticon** [comment]
This has been  implemented on _dev_. There is one downside: The step where the countdown is displayed cannot be synchronized without adding another round of communication (which I didn't do). I see two possible solutions, the second of which has been implemented on the UI side only:

- We add another round of communication that indicates that all viewers are ready but that the task has not started yet. This is a bit of overhead for a simple countdown.
- We simply start the task right away and specify a time window on the UI side during which the countdown should be displayed (e.g. during the first five seconds). Consequently, we would need to add a 5s padding to every task duration. And viewers joining t split-second late may only see a 4 or 3 second countdown.

**Comment by ppanopticon** [comment]
Needs extensive testing :-)

**Comment by lucaro** [comment]
I think this solution is fine, assuming viewers cannot cheat by reloading the page at the right moment to skip the countdown.
