### ISSUE TITLE
Soft redesign competition builder

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#310]

**Comment by lucaro** [comment]
just tested the current state of this, here are the issues I found:

- [ ] [object object] in image preview in team (see #336)
- [ ] no way to see all properties of task types
- [ ] no preview for external images
- [ ] image preview for collection images is broken
- [ ] video preview does not update correctly when switching from one task to another
- [ ] save takes very long now, maybe add a loading indicator? (also, save should not take soo long)

**Comment by sauterl** [comment]
Additionally, these points should be addressed as well (referring to the latest commit on the feature/xodus-storage branch):

- [ ] Carefully check layouting after upgrading to Angular (Material) 15
- [ ] Replace "remove task template" icon with a trash bin
- [ ] Add confirmation dialg to removing task template
- [ ] Replace re-order buttons of task templates with more intuitive drag'n'drop

**Comment by sauterl** [comment]
Ad: Re-order buttons as drag'n'drop will have to be its own work in a future release. See #410
