### ISSUE TITLE
Frontend: Reconnect WS

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#328]
Websocket does not properly reconnect upon browser reload in viewer. This should be fixed at some point.

**Comment by ppanopticon** [comment]
I cannot really reproduce this issue. If I reload my browser, WebSocket reconnects as expected.

What exactly is the issue here?

**Comment by sauterl** [comment]
Then this issue got fixed along the way...

I guess there were instances, where no websocket reconnection was established.

**Comment by ppanopticon** [comment]
Okay! So I'll close the issue and we re-open it (with more details) if the problem resurfaces.
