### ISSUE TITLE
Clear Indicator for Minimal Team Name Length

### ISSUE THREAD

**Issue by silvanheller** [dres-dev/DRES#335]
**Is your feature request related to a problem? Please describe.**
I was confused when I was trying to add a Team called "1" because the indicator was red. After trial and error, I found out that there is a minimum length.

**Describe the solution you'd like**
An indicator which points me towards the problem. For example, if 2 seconds after the first letter is typed, there still are less than 3 characters, an additional information in red could show up next to the field name.

**Describe alternatives you've considered**
- There could be a help text which is always visible
- There could be a minimum length of 1 instead of 3 for Team Names.

**Comment by ppanopticon** [comment]
Fixed in v2.
