### ISSUE TITLE
[object Object] when adding team

### ISSUE THREAD

**Issue by silvanheller** [dres-dev/DRES#336]
**Describe the bug**
Next to the select logo button, there  is an [object Object] instead of whatever would be correct.

![image](https://user-images.githubusercontent.com/14314470/170073354-704ec8ca-11f7-43e7-8097-f4ccfbfda490.png)

**To Reproduce**
1. Create new competition2. 
2. Add a Team 

**Expected behavior**

**Screenshots**

**Environment**
 - OS: Ubuntu
 - Browser: Firefox
 - DRES Version: v1.2

**Comment by lucaro** [comment]
That is currently on hold a bit, since https://github.com/dres-dev/DRES/tree/feature/xodus-storage will necessitate a 2.0 release. When we already have to break with backwards compatibility, we'll wait with larger UI changes until then as well.

**Comment by sauterl** [comment]
wontfix since the issue no longer occurs in the https://github.com/dres-dev/DRES/tree/feature/xodus-storage branch
