### ISSUE TITLE
Filter Autocompletes for AVS to prevent duplicate additions

### ISSUE THREAD

**Issue by silvanheller** [dres-dev/DRES#338]
**Is your feature request related to a problem? Please describe.**
When adding multiple items from the same object, the autocomplete functionality suggests items which are already added.

e.g. for LSC, if you enter `20160828`, the autocomplete shows always the same items first, regardless of whether they've already been added.

**Describe the solution you'd like**
Ideally, the autocomplete suggestions would not show items which are already considered correct for a task

**Comment by sauterl** [comment]
This feature is implemented in the new editor for version 2.
