### ISSUE TITLE
Total Cookie Protection of Firefox Breaks Automatic Login of Client Examples

### ISSUE THREAD

**Issue by silvanheller** [dres-dev/DRES#347]
**Describe the bug**
With the newest privacy protections from Firefox (https://blog.mozilla.org/en/products/firefox/firefox-rolls-out-total-cookie-protection-by-default-to-all-users-worldwide/), logging in to DRES in one Tab does not automatically ensure you have access from a system in another tab (e.g. vitrivr-ng). Disabling the feature makes the login work again.

I'm not particularly sure something can be done about this, but I'm filing this here anyway for reference.

**To Reproduce**
1. Use the newest Firefox with Total Cookie Protection enabled
2. Log in to a DRES Instance
3. Refresh your system instance / client example / vitrivr-ng in another tab
4. Get 401 errors

**Environment**
 - OS: MacOS
 - Browser: Firefox
 - DRES Version: v1.2.1 (or whatever is deployed at `vbs.videobrowsing.org` on 21/June)

**Comment by lucaro** [comment]
By my understanding, that's very much intended behavior from Mozilla's point of view, see https://support.mozilla.org/en-US/kb/total-cookie-protection-and-website-breakage-faq#w_why-does-total-cookie-protection-cause-site-breakage. To circumvent this, the API access token needs to be provided explicitly, as illustrated in https://github.com/dres-dev/Client-Examples/blob/main/angular-ts/src/app/app.component.ts. Did you observe this issue in the client example or in an independent implementation?
