### ISSUE TITLE
Add toggle for temporal context in Judgement view

### ISSUE THREAD

**Issue by lucaro** [dres-dev/DRES#358]
Currently, the judgement view always shows some temporal context outside the actual submissions when video sequences need to be judged. Based on user feedback, it looks like this is confusing in many cases. The instances where this context is actually required appear to be quite few. Therefore, by default, the context should not be shown. A toggle to enable the context in cases where it could be helpful should be added, so a judge can activate it when they think they need additional information.

**Comment by Thunderarea** [comment]
As a judge I agree that this change would greatly help the judging process. Thank you
