### ISSUE TITLE
Judgement Viewer usability improvements

### ISSUE THREAD

**Issue by lucaro** [dres-dev/DRES#359]
Based on user feedback, there are several usability improvements that can be made to the judgement viewer:

- [x] Show the relevant query text more prominently (i.e., larger text)
- [x] Make effect for change in query text more visible
- [x] Show keyboard shortcuts for verdicts more prominently
- [x] make buttons larger and have more intuitive colors (i.e., green for accept, red for reject, maybe yellow or blue for undecidable)
- [ ] ensure that previous playback is always cleared properly. There have been reports of audio of previous submissions still playing.

**Comment by sauterl** [comment]
This issue has mostly been addressed. Remaining work is listed in #400
