### ISSUE TITLE
Duration of random segment cannot be set

### ISSUE THREAD

**Issue by klschoef** [dres-dev/DRES#364]
When I start adding KIS tasks, a default duration of 300s is shown. When I change this duration to 20s and then add a target, it uses wrong calculations for segment_end - segment_start (not 20s diff). This is an annoying bug and I would appreciate if it could be corrected.
Thanks!

**Comment by klschoef** [comment]
Just one note: I think I may confuse task-duration with segment-duration... both are just called "duration", where can I define which one?

**Comment by lucaro** [comment]
I'm not sure I understand the issue. The 300s you referring to is the total duration of the task, the duration of the target segment or the duration for which you want the segment to be shown?
Maybe a screenshot of the editor would help to clarify?

**Comment by klschoef** [comment]
Okay, I see... the duration in Task Type and Task is always "time to solve the task". I confused it with "random segment length", which is in fact missing and completely random. So my request is actually: can we somewhere introduce a "default segment length" for segment-based tasks?

**Comment by lucaro** [comment]
I see, so the issue is that the random segment has a random duration every time, rather than a configurable one?

**Comment by klschoef** [comment]
Yes, exactly... this is actually the issue!

**Comment by lucaro** [comment]
Ok, I adjusted the title accordingly. We'll have a look at this for the next update to the editor.

**Comment by sauterl** [comment]
In version 2 there will be a (client side) default length to be set for (randomised) target segments.
