### ISSUE TITLE
End to end testing of majorly used components

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#402]
Test and verify that the system works as intended only using the UI with respect to:

- [ ] Evaluation building. Majorly used task types / task type templates etc. for campaigns such as VBS and LSC
- [ ] Evaluation running. The viewer and admin view with respect to campaigns such as VBS and LSC
- [ ] User management
- [ ] Collection management

**Comment by sauterl** [comment]
Ad "Evaluation running": Properly test submission -> verdict pipline including deduplication and judgements

**Comment by lucaro** [comment]
processes were successfully tested in VBS'24
