### ISSUE TITLE
Changes to 'General Information' are not saved for templates

### ISSUE THREAD

**Issue by ppanopticon** [dres-dev/DRES#411]
**Describe the bug**
Changes to basic properties (tab 'General Information') are not stored in new template editor.

**To Reproduce**
1. Open a an existing template in the new template editor.
2. Make a change, e.g., to the field 'Name'
3. Save
4. Reload

**Expected behavior**
After the reload, the newly entered information should be displayed. It isn't, instead, the old information is reloaded.

**Environment**
 - OS: OS X
 - Browser: Chrome
 - DRES Version: v2 (xodus-storage)

**Additional context**
From what I see, the API responsible for updating the template receives the old information instead of the newly entered one. There seems to be an issue with updating the form / model.

**Comment by lucaro** [comment]
Aren't there also some fields there, such as a template-level default media collection, that are not stored in the backend at all?

**Comment by sauterl** [comment]
Yes, there are two fields, default media collection and default length of a random segment in seconds that are client-side only. However @ppanopticon correctly pointed out that name and description weren't properly updated. This has been fixed.

**Comment by lucaro** [comment]
Would we want to store these additional fields as well? I'd think it confusing if some fields are deliberately not stored.
