### ISSUE TITLE
Issue with repeated video clip presentation?

### ISSUE THREAD

**Issue by klschoef** [dres-dev/DRES#425]
The current version (as used for LSC) seems to have an issue with repeated video clip presentation for long-running synchronous tasks. For visual KIS tasks, after the while, the video playback is not working anymore in the viewer. I am not sure if this is a true DRES bug, or if it has something to do with CloudFlare, but the text presentation (textual KIS) is working without any issue.

**Comment by lucaro** [comment]
This is difficult to reproduce. Do you have an instance where this issue can currently be observed?

**Comment by sauterl** [comment]
For future reference: In case one specific task is prolonged in the editor sgnificantly, the query description has to be adjusted accordingly, in case a `end` value was set.
In order for a query description to last as long as the task, do not set the `end` value.
