### ISSUE TITLE
DbAuditLogger soft-redesign

### ISSUE THREAD

**Issue by ppanopticon** [dres-dev/DRES#428]
In the light of our most recent refactoring, I believe the ``DBAuditLogger`` has certain design flaws that we ought to be addressed. All these thoughts are based on the assumption, that the ``DBAuditLogger`` subsystem is intended:

- As a fallback layer that allows for a replay of an evaluation in case data is lost.
- As an administrative layer for post-hoc analysis of external user interaction.

# Usage
Currently, the ``DBAuditLogger`` is used at several points in the system and it bears the question, what exactly it is we log. I would argue, that we're mainly interested in logging API interactions and thus external stimuli that influence the state of an evaluation (since the rest should be deterministic to some extent). In that spirit, ``DBAuditLogger`` interactions should be limited to the relevant API handler classes and thus should not occur in the core-logic of any of the other subsystems.

Furthermore, the ``DBAuditLogger`` should work on a best-effort basis and it should under no circumstance cause an (apparent) failure-scenario of the respective API endpoint.

# Scope
Especially in the submission subsystem, we should thing about the semantics of what we log. Do we log all incoming submission (which is what I would expect from an audit log) or do we only process incoming submissions that pass some prior validation (e.g., filtering). Thus far, we did the latter.

# Data Storage
Since the ``DBAuditLogger`` is intended as a fallback in case something goes wrong, I believe that data storage should be decoupled from the main database. This could mean a separate Xodus environment or a completely different storage mechanism (e.g., an append-only log). This will have several benefits:

- [ ] Write-transactions on one store do not interfere with the other store (less congestion).
- [ ] Since in principle, the ``DBAuditLogger`` does not need to persist information right away, we can use buffering to reduce IO which also decouples invocation in the API from actual storage of the data (= performance).
- [ ] In case of data corruption, it is unlikely that both stores will be affected, making the ``DBAuditLogger`` a truly independent subsystem.

# Other Design Goals

- **Self-containedness:** Due to the reliance of the ``DBAuditLogger`` on the main Xodus storage environment, we must always wrap invocations of tis methods in a transaction.  This should happen as part of the ``DBAuditLogger``, making it a self-contained component of the system
- ... (ideas are welcome)

**Comment by lucaro** [comment]
I completely agree that decoupling the AuditLogger from the database would be desirable. The question is what range of functionality we actually need here. It would greatly simplify things, if we were to get rid of any reading operation, at least in the API. If we were to do this, the log could operate in a 'write and forget' mode, completely independently of regular operations. Since this log is anyway only used for posthoc analysis, the only thing we would lose is the audit log display in the UI, which is anyway not all that useful. Thoughts?
