### ISSUE TITLE
Important clean-up operations / General design principles (backend)

### ISSUE THREAD

**Issue by ppanopticon** [dres-dev/DRES#429]
In the my refactoring activities, I encountered several inconsistencies in the DRES stack, which I believe should be addressed to make the architecture more self-explanatory, robust and stable.

This is probably a long-term project and this ticket should capture the main design-principles, that we want to apply (which are, of course open to discussion, this is simply a suggestion):

# API vs DB objects
I would suggest, that database objects  (classes that start with ``Db*``) should be restricted to internal use and therefore not be exposed through any of the public interfaces of the core facilities (those that the API interacts with directly). These should instead rely on the corresponding API object (classes that start with ``Api*``).

## Caching
Generally, database objects should not be kept around in memory, unless absolutely necessary. Instead, we should store IDs and retrieve the object again, once we use them. This allows us to save memory. Furthermore, it will prevent inconsistencies caused by outdated objects, that need to be re-attached to a new database session.

# Database Transactions
Generally, transactions should only take place in the core logic of the DRES stack. That is, every API endpoint that uses some of this core-logic is not allowed to spawn its own transaction. The only exception here are endpoints, that do not rely on any core logic and simply interact with the database to retrieve some information (read-only).

## Write-transactions
Write transactions should be as short-lived as possible, since Xodus does not have reconciliation mechanisms in place, in case a transaction fails. This is something that we must keep in mind.

Furthermore, and as a consequence, all write-transactions should be side-effect free and should not cause changes to the system state that might become invalid because of a transaction's failure to commit (e.g., sending WebSocket messages or updating in-memory data structures before actually having persisted the relevant information).

# Signalling and Coupling
Some of our components use explicit signals to inform other components about changes (e.g., ``RunManager.reScore()`` invocation in judgement subsystem). This leads to tight coupling, that we should try to avoid especially, since it will automatically violate some of the design principles outlined above . 

To achieve the same goal, I see two potential approaches here:

- Eliminating the data structures that rely on these signals, since they're often just bound to some cache that would otherwise be invalidated (e.g., when it comes to scores).
- Using ``TransientStoreSessionListener`` to react to changes to the data.

I could very much imagine, that this is actually quite a neat way of reacting to changes to the submissions and the necessary invalidation of scoreboards and I will try this when tackling #404.

In the short-term, we should probably do-aways with all the stateful ``Updateable`` implementations.

**Comment by sauterl** [comment]
Thank you for your insights and thoughts.

* I'm fairly certain the `Db*` vs. `Api*` design principle you outlined is what we have agreed upon. It appears to me based on your fomrulation we weren't as consistent with this principle as we wanted to be. Did you mark your findings somewhere?
* I do like your proposed id-based cacheing!
* Your proposed transaction handling seems very reasonable. I do wonder whether we can enforce this? Furthermore, I'd like to treat the CLI and REST API similarly, and enforce the transaction model there as well.
* The ``TransientStoreSessionListener` approach seems very interesting!

**Comment by sauterl** [comment]
Consier this closed
