### ISSUE TITLE
V2 Acceptance Test Round 2

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#431]
- [x] Judgement View: Various errors displayed, including the to-be-expected and handled `uncaught in Promise` (judgement verdict faster than video loading) -> Those erros should get handled properly @sauterl 
- [x] adjust time: backend delivers wrong error message -> decrease time to less than remaining results in task ending @sauterl 
- [x] Investigate whether new submission handler can answer with verdict, if available @sauterl 
- [x] viewer: target not shown if task has ended -> should display target(s) ( @sauterl )
- ~[ ] viewer: hints timer seems to be absolute and regardless of actual task time -> should display hints based on actual task time (e.g. when time is adjusted, display hints accordingly) ( @sauterl  )~ We decided to keep the hint start and end times as _ellapsed_ task time.
- [x] When evaluation terminated, state error is 500 -> should be 404 and frontend should navigate to list @lucaro 
- [x] async run is broken -> investigate and fix @lucaro 
- [x] Multi target KIS for segments ignores non-first answers @lucaro 
- [x] message about missing web-socket connection gets added multiple times over time

**Comment by sauterl** [comment]
Regarding "Hints timer seems to be absolute and regardless of actual task time":

I do remeber that we had a discussion abou these semantics and I'm not sure whether we want to change them or not:

Currently, the task hints start and end time are considered _forward_. Hence, for a hint that is displayed from seconds 30 until the end, if the task duration is adjusted such that the task ends earlier than 30s, the hint is never displayed (as in: there were never 30 seconds of the task time elapsed).

It might be worthwhile, although more complex, to have the task hints start and end time _backwards_ and _scaled_: For a task duration of 120s, a hint that displayed from seconds 30 until the end, would, in case the task duration would be adjusted to a total of 60s, be displayed from seconds elapsed 45 to 60.

What are your thoughts?

**Comment by lucaro** [comment]
I guess it makes more sense (even though it might be less immediately intuitive) to not change hint intervals when the task duration is changed. Otherwise, one would need to define *how* they are supposed to be changed, and there are again multiple options that one could argue for.

**Comment by sauterl** [comment]
Thank you for your input. I guess we'll have to stress this fact in the documentation and might even add additionaly client-side information like we do for textual targets (that they allow for regex).
