### ISSUE TITLE
Redirect on permission denied

### ISSUE THREAD

**Issue by lucaro** [dres-dev/DRES#433]
When a call is made that returns an authentication error, the frontend should redirect to the login page.

**Comment by sauterl** [comment]
Also check whether the global error handler receives a 404 redirect to login.

**Comment by sauterl** [comment]
Newly introduced functionality will redirect to the login page in case a call to _our_ backend fails with a `401`
The redirct includes the URL to the previously visited page if and only if it was not already the login page. Hopefully this fits your needs

**Comment by sauterl** [comment]
Apparently, the current mechanism in place is not as reliable as originally expected.
