### ISSUE TITLE
Disable all user interaction in viewer

### ISSUE THREAD

**Issue by lucaro** [dres-dev/DRES#434]
There should be a path/query parameter to disable all user interaction elements in the viewer. This would include the top menu bar. A use-case would be scenarios where the task viewer is embedded as an iframe in another application and no user interaction is desired.

**Comment by sauterl** [comment]
A draft to resolve this issue has been made:

By adding the matrix parameter `noUi=true` to the layout settings for the viewer, the top-bar is removed and in the async case, also the task controls. Is this what you had in mind?

**Comment by lucaro** [comment]
Great, thank you. Yes, that's pretty much what I had in mind. Based on https://github.com/dres-dev/DRES/commit/d8e5a61a0fe68eb1881a7a5705657a485f662e57 though, I cannot see any changes to the viewer itself. It would ideally also remove all interactable UI elements, such as the menu to configure the visible components and the buttons shown for async evaluations.
