### ISSUE TITLE
DRES 2.0.0 RC3 cannot log when more than one evaluation is running

### ISSUE THREAD

**Issue by klschoef** [dres-dev/DRES#457]
If more than one evaluation is active (i.e., with a running task) the query-log and result-log is not working. It returns 409 (conflict). You can currently test this with vbs.videobrowsing.org, where we have two evaluations running.

**Comment by lucaro** [comment]
Logging across multiple evaluations with overlapping participants is an edge-case not currently supported. Would this be needed for VBS'24?

**Comment by klschoef** [comment]
It is not VERY important for VBS 2024, but still it would be good to fix this soon, because even now we use several evaluations at the same time to test different task types.

**Comment by lucaro** [comment]
Ok, we'll see what we can do. This will necessitate an API change, though.

**Comment by klschoef** [comment]
Thank you! The API change should not be a big issue, I hope.

**Comment by sauterl** [comment]
This has been addressed in [RC4](https://github.com/dres-dev/DRES/releases/tag/2.0.0-RC4)
