### ISSUE TITLE
Additional, dedicated endpoint(s) for raw score download

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#99]
Dedicated endpoint(s) for enriched score export for plotting with additional tools.

**Comment by lucaro** [comment]
Not sure we need image exports. I would stick with data exports, but with more information. If this information is to be plotted afterwards, there already are a sufficient number of solutions for that...

**Comment by sauterl** [comment]
As mentioned in #98, apexcharts/apexcharts.js#1669 is already fixed.
However, I agree that we might want to provide endpoints to download data, enhanced for plotting (with external tools).
I adjusted the issue's description accordingly and moved to the 1.0.0 milestone
